import Navbar from "@/components/navbar";

export const metadata = {
  title: "Project | Admin Dashboard",
  description: "Generated by create next app",
};

const ProjectHome = ({params}: {params: { id: string }}) => {
   
  return (
    <>
    <Navbar />
      <div className="grid grid-cols-4 gap-4 p-10">
        <h3>Project {JSON.stringify(params.id)} home</h3>
      </div>
    </>
  );
};

export default ProjectHome;
