import { Inter } from 'next/font/google'
import Login  from '@/app/login/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Home | Admin Dashboard",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <h1>hi there</h1>
    <Login />
    </>
  )
}
