import { Figtree } from "next/font/google";
import Login from "@/app/login/page";

const figtree = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Login | Admin Dashboard",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className={figtree.className}>
      <Login />
    </div>
  );
}
