import Navbar from "@/components/navbar";
import ClickableCard from "@/components/ui/card"
import projects from "../data/projects";

export const metadata = {
  title: "Home | Admin Dashboard",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <Navbar />
      <div className="grid grid-cols-4 gap-4 p-10">
        {projects.map((item, index) => <ClickableCard key={index} data={item}/>)}
      </div>
    </>
  );
};

export default Home;
