import Navbar from "../../components/navbar";

export const metadata = {
  title: "Home | Admin Dashboard",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <>
      <Navbar />
      <div className="flex flex-col md:h-screen">
        <h1>Hihiihihi</h1>
      </div>
    </>
  );
};

export default Home;
